version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Monta o diretório do projeto para hot reload
      - ./uploads:/app/uploads  # Monta o diretório de uploads
      - ./logs:/app/logs  # Monta o diretório de logs com permissões corretas
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "source activate video_retalking && celery -A app.core.celery_app worker --loglevel=info"
    volumes:
      - .:/app  # Monta o diretório do projeto para atualizações de código
      - ./uploads:/app/uploads  # Monta o diretório de uploads
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "source activate video_retalking && celery -A app.core.celery_app beat --loglevel=info"
    volumes:
      - .:/app  # Monta o diretório do projeto para atualizações de código
      - ./uploads:/app/uploads  # Monta o diretório de uploads
      - ./celerybeat-schedule:/app/celerybeat-schedule  # Monta o diretório para o agendador do Celery Beat
    depends_on:
      - redis
