version: '3.7'

services:
  web:
    build: .
    command: /bin/bash -c "source activate video_retalking && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: /bin/bash -c "source activate video_retalking && celery -A app.core.celery_app worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build: .
    command: /bin/bash -c "source activate video_retalking && celery -A app.core.celery_app beat --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis
