
version: '3.8'

services:
  api:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DATABASE_URL: "sqlite:///./test.db"
    volumes:
      - ./app/processed_videos:/app/processed_videos
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  worker:
    build: ./app
    command: celery -A celery_config.celery_app worker --loglevel=info
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ./app/processed_videos:/app/processed_videos
    depends_on:
      - redis

volumes:
  redis-data:
    