version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount the project directory for hot reload
      - ./uploads:/app/uploads  # Mount the uploads directory
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "source activate video_retalking && celery -A app.core.celery_app worker --loglevel=info"
    volumes:
      - .:/app  # Mount the project directory for code updates
      - ./uploads:/app/uploads  # Mount the uploads directory
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "source activate video_retalking && celery -A app.core.celery_app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app  # Mount the project directory for code updates
      - ./uploads:/app/uploads  # Mount the uploads directory
      - ./celerybeat-schedule:/app/celerybeat-schedule  # Mount the directory for Celery Beat schedule
    depends_on:
      - redis
