version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Monta o diretório do projeto para permitir hot reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "source activate video_retalking && celery -A app.core.celery_app worker --loglevel=info"
    volumes:
      - .:/app  # Monta o diretório do projeto para que o código seja atualizado no worker
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "source activate video_retalking && celery -A app.core.celery_app beat --loglevel=info"
    volumes:
      - .:/app  # Monta o diretório do projeto para que o código seja atualizado no beat
    depends_on:
      - redis
